apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: my-echo-task
  namespace: ci
spec:
  params:
    - name: message
      description: the message to echo
      type: string
  steps:
    - name: run
      image: localhost/tekton-builder-image-ubuntu-with-kubectl:latest
      imagePullPolicy: Never
      script: |
        echo "$(params.message)"
