apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: builder
  namespace: ci
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "tasks", "pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["get", "list"]
