FROM ubuntu:jammy

SHELL ["/bin/bash", "-c"]

RUN apt update && apt upgrade -y && \
  export DEBIAN_FRONTEND="noninteractive" && \
  export TZ="Europe/Stockholm" && \
  apt install -y \
  curl \
  jq

RUN \
  mkdir /tmp/kubectl-install && \
  cd /tmp/kubectl-install && \
  curl -L https://dl.k8s.io/release/v1.34.1/bin/linux/amd64/kubectl --output kubectl && \
  sha512sum -c <(echo "bc4f4c98a2c4f7d872e5a8024dd0f47f73e1a5a6c8b833f265e7453c3c31f23555c3df1d921c5b3e8a0f6a1aae4954f0b5141db9c396c4206c947206eb34a398 kubectl") && \
  install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl && \
  cd / && \
  rm -rf /tmp/kubectl-install
